"""Added Vendor table

Revision ID: 25acf793d54a
Revises: 216c51cf395d
Create Date: 2025-03-31 18:27:39.445375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '25acf793d54a'
down_revision = '216c51cf395d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('contact')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('address', mysql.TEXT(), nullable=False))

    # ### end Alembic commands ###
